sonar.projectKey=service-converter
sonar.projectName=Service Converter (Django)
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=\
  **/migrations/**,\
  **/__pycache__/**,\
  **/tests/**,\
  **/venv/**,\
  db.sqlite3,\
  manage.py,\
  **/logs/**,\
  **/diagrams/**,\
  **/docs/**,\
  **/examples/**,\
  **/*.pyc

sonar.python.version=3
sonar.sourceEncoding=UTF-8
sonar.scm.disabled=true
