# Generated by Django 6.0.1 on 2026-04-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagramhistory',
            name='source_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
